config/routes.rb
Rails.application.routes.draw do
  get 'users/signin'

  get 'users/home'

  get 'users/login'

  get 'retirer' ,to: 'pages#retirer' , as: :retirer
  get 'deposer' ,to: 'pages#deposer' , as: :deposer
  get 'contact' ,to: 'pages#contact' , as: :contact

  root 'pages#home'

  get 'users/home' => 'users#home'
  post 'users/home' => 'users#home'
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  get 'users/signin' => 'users#signin'
  post 'users/signin' => 'users#check'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def retirer
  end
  def deposer
  end
  def contact
  end
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
  end

  def login
  end

  def signin
  end

  def check
    @current_user = User.where(name: params[:name], password: params[:password]).first
    if @current_user
      flash[:info] = "Bienvenue #{@current_user.name} !"
      redirect_to "/users/home"
    else
      flash[:info] = "Échec de la connexion"
      redirect_to "/users/login"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furnitroc</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <title>Furnitroc</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Caveat+Brush" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  </head>

  <body>
    <div><%= flash[:info] %></div>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.slim
.background

  h1
    | Contact

  h4
    | Furnitroc

  p
    | 64 rue du mobilier
    br
    | 42000
    br
    | Saint-Etienne

  p
    | Téléphone : 06 75 43 21 98

  = mail_to "furnitroc@gmail.com", "Contact par mail",
    :subject => "formulaire rails",
    #:cc => "unAutre@email.com",
    #:body => "un message...",
    :encoding => "javascript"

  p
    | Horaires : 10h / 17h


  iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2799.658787825411!2d4.388469415486612!3d45.43637917910068!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f5aeac765b1de9%3A0xf6bcc4893ecc676b!2s10+Rue+Georges+Dupr%C3%A9%2C+42000+Saint-%C3%89tienne!5e0!3m2!1sen!2sfr!4v1516458821140" width="80%" height="450px" frameborder="0" style="border:0" allowfullscreen


  .back
    = link_to root_url do
      | Retourner à l'accueil

app/views/pages/deposer.html.slim
.background

  .icon
    = link_to root_url do
      = image_tag "icon.jpg", class: "icon_img"

  h1
    | Proposez
  h5
    | Déposez un ou plusieurs meubles au troc !

  = form_tag("/recherche", :method => "get") do

    => label_tag(:product_field, "Produits")
    = text_field(:p , :product_field, :class=>'grise', :size=>'20')
    br
    p
      | Type
      select(
        data-is-select = ""
      )
        option (
          value = "test"
        )
          | table
        option (
          value = "test1"
        )
          | assise
        option (
          value = "test1"
        )
          | meubles
    br
    => label_tag(:text_area_tag, "Description")
    = text_area_tag(:message, "", size: "24x6", placeholder: "Message")
    br
    br
    => label_tag(:file_field_tag, "Sélectionner une photo")
    = file_field_tag :mon_fichier
    br
    br
    = check_box_tag(:troc)
    =< label_tag(:troc, "Troc")
    br
    = check_box_tag(:don)
    =< label_tag(:don, "Don")
    br
    br
  = submit_tag "Envoyer", :name => nil, :id => "submit"

app/views/pages/home.html.slim
.background

  .icon
    = link_to root_url do
      = image_tag "icon.jpg", class: "icon_img"

  .users
    .connexion
      a href="/users/login"
        | S'identifier

    .inscription
      a href="/users/signin"
        | S'inscrire

  .lien
    = link_to "Déposer", deposer_path, class: 'style_lien'
    br
    br
    = link_to "Retirer", retirer_path, class: 'style_lien'

  .titre
    h1
      | Furnitroc
    h5
      | Give your office furniture a new life !
  .text
    p
      | Votre entreprise change de mobilier ? Nouvelle décoration pour votre bureau ?
    p
      | Pensez à Furnitroc !
    p
      | Parce qu'une entreprise peut compter sur son équipe mais aussi sur un mobilier fidèle au poste jours après jours...
    p
      | Notre équipe vous mets en relation avec d'autres entreprises, collectivités ou associations pour que vos meubles soient toujours utiles.

.who
  h3
    | Qui somme nous ?
  a
    button.btn-primary(
      type = "button"
    )
      | En savoir +
    p.bg-info
      | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae hic voluptate eum, sit possimus nostrum, ducimus beatae? Voluptatibus, harum. Modi error consectetur quasi alias quas obcaecati dolorem quam! Quisquam, impedit!

    javascript:
     $('.bg-info').toggle(0, 0);
     $('button').click(function(){
       $('.bg-info').toggle('hide');
     });

.background2

  br
  br

  .step1
    h4
      | 1
    p
      | Simple et efficace
    p
      | Inscription sur le site

  .step2
    h4
      | 2
    p
      | Proposez du mobilier
    p
      | Remplir le petit formulaire
    p
      | N'oubliez pas de choisir entre le troc ou le don

  .step3
    h4
      | 3
    p
      | Liste des interessés
    p
      | Trouvez un partenaire

  .step4
    h4
      | 4
    p
      | Mise en contact
    p
      | Discutez librement

  .step5
    h4
      | 5
    p
      | Ouvrir une mission
    p
      | Remplir l'ordre de mission
    p
      | Le valider une fois la mission accomplie

  .equipe

    = image_tag "http://deothemes.com/envato/enigma/html/img/team_1.jpg", class: "team"
    = image_tag "http://deothemes.com/envato/enigma/html/img/team_1.jpg", class: "team"
    = image_tag "http://deothemes.com/envato/enigma/html/img/team_1.jpg", class: "team"
  br
  .presentation
    p.prenom
      | Jimmy
    p.prenom
      | Sarah
    p.prenom
      | Georgie

  footer

    .contact

      i class= "fa fa-paper-plane-o"
      =< link_to "Contact", contact_path, class: 'lien_contact'

  br
  br

    .social-btns
        a(
          class = "btn facebook"
          href  = "https://www.facebook.com"
          target = "_blank"
        )
          i class="fa fa-facebook"
        a(
          class = "btn twitter"
          href  = "https://twitter.com"
          target = "_blank"
        )
          i class="fa fa-twitter"
        a(
          class = "btn google"
          href  = "https://google.com"
          target = "_blank"
        )
          i class="fa fa-google"
        a(
          class = "btn skype"
          href  = "https://skype.com"
          target = "_blank"
        )
          i class="fa fa-skype"

app/views/pages/retirer.html.slim
.background

  .icon
    = link_to root_url do
      = image_tag "icon.jpg", class: "icon_img"
  h1
    | Recherche
  p
    | Trouver un meuble pour votre entreprise

  = form_tag("/recherche", :method => "get") do
    = search_field_tag :recherche, params[:recherche]
    = submit_tag "Recherche", :name => nil, :id => "submit"

  br
  br

  .card
    i.far.fa-lightbulb
    p
      | Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, officiis, autem, adipisci in obcaecati aliquid magni doloribus reprehenderit hic nemo accusamus distinctio consectetur accusantium? Reiciendis ratione fugit aliquam vitae delectus.

  br

  .product_card
    center
      p
        | Produit 01
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
        br
        br
      = link_to "Voir", "#", class: ''

  .product_card
    center
      p
        | Produit 02
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
      = link_to "Voir", "#", class: ''

  .product_card
    center
      p
        | Produit 03
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
      = link_to "Voir", "#", class: ''

  .product_card
    center
      p
        | Produit 04
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
      = link_to "Voir", "#", class: ''

  .product_card
    center
      p
        | Produit 05
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
      = link_to "Voir", "#", class: ''

  .product_card
    center
      p
        | Produit 06
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
      = link_to "Voir", "#", class: ''

  .product_card
    center
      p
        | Produit 07
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
      = link_to "Voir", "#", class: ''

  .product_card
    center
      p
        | Produit 08
      = image_tag "icon.jpg",
        class: "img_product",
        style: "width: 20%"
      = link_to "Voir", "#", class: ''









  // rentacar
  .rentacar
    p
      | Besoin d'un véhicule pour allez récupérer vos meubles ?
    p
      | Louez un véhicule chez l'un de nos partenaires...

app/views/partials/_en_savoir_plus_js.html.erb
<script>
$('.bg-info').toggle(0, 0);
$('button').click(function(){
  $('.bg-info').toggle('hide');
});
</script>

app/views/users/home.html.slim
.background

  h1
    | Mon Compte

  .aside
    h1
      | Bonjour

    li
      a href="#monTableau2"
        | Mon tableau de bord
    li
      a href="#monTableau2"
        | Mon profil
    li
      a href="#monTableau2"
        | Mes échanges
    li
      a href="#monTableau2"
        | Mon tableau de bord




  .container

    a href="#"
    h3
      | Mon profil
    p
      | Modifier mes informations, mon mot de passe et  mes abonnements Newsletter




  .back
    = link_to root_url do
      | Retourner à l'accueil

app/views/users/login.html.slim
.background

  h1
    | Connexion

  = form_tag "home", method: :post do

    => label_tag(:name_field, "Identifiant")
    = text_field(:p , :name_field, :class=>'grise', :size=>'20')
    br
    br
    => label_tag(:password_field_tag, "Mot de passe")
    = password_field_tag(:password)
    br
    br
    = submit_tag "Connexion", :name => nil, :id => "submit"


  .back
    = link_to root_url do
      | Retourner à l'accueil

app/views/users/signin.html.slim
.background

  h1
    | Inscription

  = form_tag "/users/login", method: :post do

    input data-icon="" name="sex" type="radio" value="f"
    input data-icon="" name="sex" type="radio" value="m"
    br
    br
    => label_tag(:name_field, "Nom")
    = text_field(:p , :name_field, :class=>'grise', :size=>'20')
    br
    br
    => label_tag(:first_name_field, "Prénom")
    = text_field(:p , :first_name_field, :class=>'grise', :size=>'20')
    br
    br
    => label_tag(:email_field, "Mail")
    = email_field(:user, :address)
    br
    br
    => label_tag(:password_field_tag, "Mot de passe")
    = password_field_tag(:password)
    br
    br
    => label_tag(:telephone_field, "Téléphone")
    = telephone_field(:user, :phone)
    br
    br
    => label_tag(:adress_field, "Adresse")
    = text_field(:p , :adress_field, :class=>'grise', :size=>'20')
    br
    br
    = submit_tag "S'inscrire", :name => nil, :id => "submit"


  .back
    = link_to root_url do
      | Retourner à l'accueil